services:
  server:
    build:
      context: ./server
    volumes:
      - ./assets:/assets
    ports:
      - 3000:3000
    networks:
      - app-network

  service:
    build:
      context: ./service
    expose:
      - 6000
    volumes:
      - ./assets:/assets
    networks:
      - app-network

volumes:
  assets:

networks:
  app-network:
